### ISSUE TITLE
Unable to add station to favourites, right click menu is not working

### ISSUE THREAD

**Issue by outlying** [SmokSmog/smoksmog-windows#33]
After right click on any station, all I got is this small white rectangle 

SmokSmog Beta for Windows
Version: 2.0.165
OS: Windows 8.1

![Screenshot](http://2.1m.yt/EK_rWP4.png)

**Comment by damiankras** [comment]
Yep it is fixed and will be in new Beta release this week

**Comment by damiankras** [comment]
fixed and released in 2.0.224 version
